#!/usr/bin/env bash

# helper function to install config
install () {
	[[ -d "$PWD/os-specific/$1" ]] && cp -faTs "$PWD/os-specific/$1" "$HOME/.config/zsh"
}

# detect OS and symlink
case "$OSTYPE" in
	darwin*) install macos;;
esac

# detect distro and symlink
[[ "$OSTYPE" = linux* ]] || exit
[[ -e /etc/os-release ]] || exit
# dumb-parse /etc/os-release ourselves, to avoid sourcing
IFS== read -r _ id < <(grep ^ID= /etc/os-release)
case "$id" in
	arch) install arch;;
esac
